### ISSUE TITLE
infer single rgb image

### ISSUE THREAD

**Issue by PredyDaddy** [Aaditya-Prasad/consistency-policy#5]
Hello, thank you for your excellent work. I would like to ask, if I only have an RGB image, how can I generate the corresponding grasping path? Which script in the repository should I use?

**Comment by Aaditya-Prasad** [comment]
I'm not sure I understand your question. Do you mean that your only observations are RGB images? You will need to update the corresponding config file to reflect this and then train a policy. The policy + config will then be able to complete inference when given the appropriate observations, as in our example notebook.

**Comment by PredyDaddy** [comment]
> I'm not sure I understand your question. Do you mean that your only observations are RGB images? You will need to update the corresponding config file to reflect this and then train a policy. The policy + config will then be able to complete inference when given the appropriate observations, as in our example notebook.

Thanks
