### ISSUE TITLE
model_ema not used in action prediction

### ISSUE THREAD

**Issue by yksheng** [Aaditya-Prasad/consistency-policy#8]
Hi authors,
I noticed that in ctm_policy.py, the self.use_ema flag is not actually used? During the conditional_sample method, shoud we use the flag here to determine whether or not we should use the ema_model in the _forward pass?

**Comment by Aaditya-Prasad** [comment]
I didn't actually find benefits from using the ema_model for inference so I didn't ensure that functionality was maintained; should be an easy change if you want to use the ema model
